//
// Created by aogun on 2021/2/18.
//

#ifndef MP4VIEWER_VERSION_H
#define MP4VIEWER_VERSION_H

#define MP4_VIEWER_VERSION_MAJOR    0
#define MP4_VIEWER_VERSION_MINOR    1
#define MP4_VIEWER_VERSION_PATCH    3

#endif //MP4VIEWER_VERSION_H
